server.port=1234
custom.kafka_topic_in=topicIn
custom.kafka_topic_out=topicOut
custom.delivery_delay=1500
custom.kafka_topic_listen_consumerGroup=CustomConsumerIdGroup
custom.kafka_brokers=localhost:19092,localhost:19093,localhost:19094
custom.kafka_truststore_location=file:./truststore.pfx
custom.kafka_truststore_pass=omnipass123
custom.kafka_truststore_type=PKCS12
custom.kafka_keystore_location=file:./keystore.pfx
custom.kafka_keystore_pass=omnipass123
custom.kafka_keystore_type=PKCS12


custom.publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE42f9zAbPDc1kl2043l8Qbn8LZ4s0/Cw0VtBdDmi9fjcml+b7Iz8Zh/CB5nFj4vEYOmpk2EkX1uny7SoVunVpWA==
custom.privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCCYgSV3sgFSMc0WJusfxCbKfFsXh8UlXXaqAi1F/DRBTQ==
custom.xCoordinate=AONn/cwGzw3NZJdtON5fEG5/C2eLNPwsNFbQXQ5ovX43
custom.yCoordinate=Jpfm+yM/GYfwgeZxY+LxGDpqZNhJF9bp8u0qFbp1aVg

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true

spring.output.ansi.enabled=always

# logging.level.org.apache.kafka=ERROR
logging.level.org.apache.kafka=INFO

# logging.pattern.console=%d{HH:mm:ss.SSS} %-5level traceId=%X{traceId} %logger{18} - %msg%n
# logging.pattern.console=%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan(traceId=)%magenta(%X{traceId:-}) %yellow(%logger{18}) %gray(-) %msg%n
# logging.pattern.console=%d{HH:mm:ss.SSS} %clr(%-5level){TRACE=faint,DEBUG=faint,INFO=green,WARN=yellow,ERROR=red,FATAL=red} %clr(traceId=){cyan}%clr(%X{traceId:-no-trace}){magenta} %clr(%logger{18}){yellow} %clr(-){faint} %msg%n


# Auto-cleaner settings
app.cleaner.retention-minutes=1
app.cleaner.interval-ms=60000

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Web GUI - enable console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
