server.port=1234
custom.kafka_topic_listen=topicIn
custom.kafka_topic_write=topicOut
custom.delivery_delay=1500
custom.kafka_topic_listen_consumerGroup=CustomConsumerIdGroup
custom.kafka_brokers=localhost:19092,localhost:19093,localhost:19094
custom.kafka_truststore_location=file:./truststore.pfx
custom.kafka_truststore_pass=omnipass123
custom.kafka_truststore_type=PKCS12
custom.kafka_keystore_location=file:./keystore.pfx
custom.kafka_keystore_pass=omnipass123
custom.kafka_keystore_type=PKCS12

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true

spring.output.ansi.enabled=always

# logging.level.org.apache.kafka=ERROR
logging.level.org.apache.kafka=INFO

# logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level [traceId=%X{traceId}] %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level traceId=%X{traceId} - %msg%n
