server.port=1234
custom.kafka_topic_listen=topicIn
custom.kafka_topic_write=topicOut
custom.delivery_delay=1500
custom.kafka_topic_listen_consumerGroup=CustomConsumerIdGroup
custom.kafka_brokers=localhost:9092,localhost:9093,localhost:9094
custom.kafka_truststore_location=file:./truststore.pfx
custom.kafka_truststore_pass=omnipass123
custom.kafka_truststore_type=PKCS12
custom.kafka_keystore_location=file:./keystore.pfx
custom.kafka_keystore_pass=omnipass123
custom.kafka_keystore_type=PKCS12

logging.pattern.console=%d{dd-MM-yy_HH:mm:ss.SSS} %-5level %msg%n

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true